### ISSUE TITLE
Seams not working script expressions.

### ISSUE THREAD

**Issue by 0x55AAh** [pacifica/python-jsonpath2#11]
Seams not working script expressions like $.store.book[(@.length-1)].title.
Filters like $.store.book[?(@.length > $.limit)] not working also. Is that ok?

**Comment by dmlb2000** [comment]
@markborkum can you confirm this?

**Comment by 0x55AAh** [comment]
Yep,
```
from jsonpath2.path import Path
$.store.book[(@.length-1)].title
```
ValueError: line 1:13 mismatched input '(' expecting {'*', ':', '?', STRING, NUMBER}
This code raise ValueError

Same thing with filters.
Pkg version 0.1.0. Installed from pip. Python 3.6.5

**Comment by dmlb2000** [comment]
@0x55AAh The correct path to use is the following
```
>>> from jsonpath2.path import Path
>>> Path.parse_str('$.store.book[-1].title')
<jsonpath2.path.Path object at 0x000001603B375940>
```

the `.length` operator is not part of the language we support string slices though.

However, the second path is more a language parse issue, maybe a subscriptable needs to include an optional jsonpath as well.

**Comment by 0x55AAh** [comment]
> the `.length` operator is not part of the language we support array slices though.
Its okay. But my case is that i need script expressions.
I have a user profile stored in database.
Profile structure is:
```
{
    ...
    "sections": {
        "0": {
            ...
        },
        ...
        "n": {
            ...
        },
    }
    "current_section": 0
    ...
}
```
And what would be better is make the only request:
$.sections[($.current_section)]
Now i need to make 2 requests:
$.current_section
$.sections[<previously_saved_current_section>]

**Comment by markborkum** [comment]
@dmlb2000 Can confirm. The current implementation has three limitations:

1. No functions (such as: array "length", object "keys", or arithmetic operators).
2. Expressions cannot be used as subscript indices.
3. Literal values are always right operands in expressions.

As mentioned, many, but not all, uses for the array "length" function can be replaced with the array slice syntax.

**Comment by dmlb2000** [comment]
Should be closed at this point.
