### ISSUE TITLE
The pypi page doesn't link to this repository

### ISSUE THREAD

**Issue by LogicalDash** [pacifica/python-jsonpath2#15]
Normally, when I click the "Homepage" link on a pypi project, I expect it to take me to the repository where the project is kept, if it doesn't have a "real" website. But in the case of jsonpath2, that link takes me to ... the same pypi page I am already looking at. If I've found out about jsonpath2 from pypi and I want to check out the repository, I have to Google for it.

The "Homepage" link on pypi should lead to https://github.com/pacifica/python-jsonpath2

**Comment by dmlb2000** [comment]
@LogicalDash Good catch, is there some documentation or guidelines that can be referenced? I hate guessing on these things. Should it go to the ReadtheDocs page?

**Comment by dmlb2000** [comment]
Looks like the example tutorial does mention using the code hosting service.
 ```
url is the URL for the homepage of the project. For many projects, this will just be a link to GitHub, GitLab, Bitbucket, or similar code hosting service
```
https://packaging.python.org/tutorials/packaging-projects/
