### ISSUE TITLE
[feature] Path to matched values

### ISSUE THREAD

**Issue by niflostancu** [pacifica/python-jsonpath2#19]
### jsonpath2 version
0.1.0

### Scenario:
Hi.

I need to get the full path to a matched value. Primarily, because I need to modify it.

__Example:__
Let's say we have:
```json
{"values": [
    {"type": 1, "value": 2},
    {"type": 2, "value": 3},
    {"type": 1, "value": 10},
]}
```
Currently, if I use an expression to match some values (e.g., `"$.values.*[?(@.type = 1)].value"`), it will return `MatchData` objects containing several properties (`current_value` is the string that I wish to get the path / modify) but none of them allow me to rebuild the full path to that value.

### Expected Result:
I would like to be able to either get the full root path as a list of keys (e.g., `["values", 0, "value"]`), or having a MatchData object provide a reference to the parent object and its matched key name (e.g., reference to the `{"type", "value"}` object + the matched `"value"` key).

I can come with a pull request if you can tell me the preferred way of implementing this.

**Comment by markborkum** [comment]
Hi @niflostancu,

The JSONPath to the `current_value` attribute of an instance of the `MatchData` class is provided by the `node` attribute.

To extract the sequence of subscripts (instances of the `Subscript` class) from an instance of the `MatchData` class, use something like the following:

```python
#!/usr/bin/python3

import json
import typing

from jsonpath2.node import Node
from jsonpath2.nodes.root import RootNode
from jsonpath2.nodes.subscript import SubscriptNode
from jsonpath2.nodes.terminal import TerminalNode
from jsonpath2.path import Path
from jsonpath2.subscript import Subscript

data = json.loads("{\"values\": [{\"type\": 1, \"value\": 2},{\"type\": 2, \"value\": 3},{\"type\": 1, \"value\": 10}]}")

path = Path.parse_str("$.values.*[?(@.type = 1)].value")

def get_subscripts(node: Node) -> typing.List[typing.List[Subscript]]:
    return get_subscripts_(node, [])

def get_subscripts_(node: Node, accumulator: typing.List[typing.List[Subscript]]) -> typing.List[typing.List[Subscript]]:
    if isinstance(node, RootNode):
        return get_subscripts_(node.next_node, accumulator)
    elif isinstance(node, SubscriptNode):
        accumulator.append(node.subscripts)
        return get_subscripts_(node.next_node, accumulator)
    elif isinstance(node, TerminalNode):
        return accumulator

for match_data in path.match(data):
    print(f"Value: {match_data.current_value}")
    print(f"JSONPath: {match_data.node.tojsonpath()}")
    print(f"Subscripts: {get_subscripts(match_data.node)}")
    print("")
```

The snippet above iterates over the match results, prints the value and JSONPath and then prints the list of subscripts. The list of subscripts is constructed by traversing the structure of the abstract syntax tree for the JSONPath.

The results [modulo the memory addresses] are:
```
Value: 2
JSONPath: $["values"][0]["value"]
Subscripts: [[<jsonpath2.subscripts.objectindex.ObjectIndexSubscript object at 0x10f6a3278>], [<jsonpath2.subscripts.arrayindex.ArrayIndexSubscript object at 0x10f6a37b8>], [<jsonpath2.subscripts.objectindex.ObjectIndexSubscript object at 0x10f6a3390>]]

Value: 10
JSONPath: $["values"][2]["value"]
Subscripts: [[<jsonpath2.subscripts.objectindex.ObjectIndexSubscript object at 0x10f6a3278>], [<jsonpath2.subscripts.arrayindex.ArrayIndexSubscript object at 0x10f6a3978>], [<jsonpath2.subscripts.objectindex.ObjectIndexSubscript object at 0x10f6a3390>]]
```

The first subscript is the `"values"` key. The second subscript is the index of the `{"type":"value"}` object. The third subscript is the `"value"` key.

Note that the result (the list of subscripts) is a *list of lists*. This is because instances of the `SubscriptNode` class are constructed using zero or more instances of the `Subscript` class.

**Comment by niflostancu** [comment]
Oh, got it, thanks.

I thought that the node represented the original AST, not a rewritten one containing the actual indices / keys.
So... does the library guarantee that the resulting subscripts will be instances of final subscript types containing the computed indices (ArrayIndexSubscript, ObjectIndexSubscript, not slices / wildcards / functions)?
I think this behavior needs to be documented.

**Comment by markborkum** [comment]
@niflostancu, the JSONPath to the value of the `current_value` attribute is the "absolute path" with respect to the value of the `root_value` attribute. The JSONPath is composed of array indices, object indices and function calls only, where the arguments for function calls are either JSONPaths or JSON values.
