### ISSUE TITLE
Simple query doesn't work

### ISSUE THREAD

**Issue by retr0h** [pacifica/python-jsonpath2#36]
I can't seem to make a simple query work.

### jsonpath2 version

jsonpath2==0.4.1

### Platform Details

Mac OS

### Steps to Reproduce:

```
import json
import jsonpath2 as jsonpath

k = {'foo': ['bar', 'baz']}

j = json.dumps(k)
__filter = '$.foo[0]'

print([m.current_value for m in jsonpath.match(__filter, j)])
```

Output

```
[jodewey:~/git/ansiblectl]   : host-filtering(+25/-2)+* ± python ansiblectl/cmd/test.py
[]
```

Changing the filter to '$' results in:

```
['{"foo": ["bar", "baz"]}']
```

Ultimately I'm trying to simply query a list but nothing seems to work.

```
import json
import jsonpath2 as jsonpath

k = ['bar', 'baz']

j = json.dumps(k)
__filter = '$[0]'

print([m.current_value for m in jsonpath.match(__filter, j)])
```

```
[jodewey:~/git/ansiblectl]   : host-filtering(+25/-2)+* ± python ansiblectl/cmd/test.py
[]
```

These queries work perfectly fine on https://jsonpath.com/

**Comment by markborkum** [comment]
@retr0h, Thanks for getting in touch!

In the steps to reproduce, the `match` method is evaluated with the string `j` as the second argument and not the dict `k`, where `j` is the JSON serialization of `k`. The string `j` does not have a "foo" attribute, so the result set is empty.

The following code should give the expected result:

```python
import jsonpath2 as jsonpath

k = {'foo': ['bar', 'baz']}

__filter = '$.foo[0]'

print([m.current_value for m in jsonpath.match(__filter, k)])
# => ['bar']
```

**Comment by retr0h** [comment]
Thanks @markborkum
