### ISSUE TITLE
Update ANTLR Runtime > 4.7

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/python-jsonpath2#45]
### jsonpath2 version
v0.4.3
### Platform Details
Any
### Scenario:
Installing `jsonpath2`
### Steps to Reproduce:
1. `pip install jsonpath2`
### Expected Result:
Install a set of dependencies that are current and supported.
### Actual Result:
`antlr4-python3-runtime` is locked at version `4.7.1` and is not current we should update this.

**Comment by aalquist** [comment]
I'm noticing Python 3.7 installs of my tool are breaking for some users. I'm also seeing my TravisCI Python 3.7 build failing. There might be an issue with Python 3.7 and ANTLR 4.7.1.


`
Collecting jsonpath2==0.4.3
  Downloading jsonpath2-0.4.3-py3-none-any.whl (34 kB)
Collecting antlr4-python3-runtime==4.7.2
  Downloading antlr4-python3-runtime-4.7.2.tar.gz (112 kB)
  Preparing metadata (setup.py) ... [?25l- error
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31mÃ—[0m [32mpython setup.py egg_info[0m did not run successfully.
  [31mâ”‚[0m exit code: [1;36m1[0m
  [31mâ•°â”€>[0m [31m[22 lines of output][0m
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "<string>", line 36, in <module>
  [31m   [0m   File "<pip-setuptools-caller>", line 14, in <module>
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
  [31m   [0m     from setuptools.dist import Distribution
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
  [31m   [0m     from ._importlib import metadata
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
  [31m   [0m     disable_importlib_metadata_finder(metadata)
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
  [31m   [0m     import importlib_metadata
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
  [31m   [0m     __version__ = version(__name__)
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
  [31m   [0m     return distribution(package).version
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution
  [31m   [0m     return Distribution.from_name(package)
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name
  [31m   [0m     dists = resolver(name)
  [31m   [0m   File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
  [31m   [0m     found = self._search_paths(context.name, context.path)
  [31m   [0m AttributeError: 'str' object has no attribute 'name'

`
