### ISSUE TITLE
Filters are not implemented per spec

### ISSUE THREAD

**Issue by SimplicityGuy** [pacifica/python-jsonpath2#51]
### jsonpath2 version
0.4.4

### Platform Details
macOS Catalina, Python 3.8.4

### Scenario:
In test case 10, you have:
```python
expr = Path.parse_str('$..book[*][?(@.author = "Nigel Rees")]')
```
This seems correct. The behavior in `jsonpath2` is correct though in http://jsonpath.com the behavior is different and is incorrect.

Another query that should result in the same results is:
```python
expr = Path.parse_str('$..book[?(@.author = "Nigel Rees")]')
```
This should return a `list of dict` that filters only the author. In `jsonpath2` this yields no results (and empty list). Yet on http://jsonpath.com, this works fine.

My understanding of the JsonPath spec is that this second query is valid and should result in what `jsonpath2` is doing in test case #10. This understanding comes from the section on the [JsonPath spec](https://goessner.net/articles/JsonPath/):
//book[price<10] | $..book[?(@.price<10)] | filter all books cheapier than 10
-- | -- | --

**Comment by markborkum** [comment]
@SimplicityGuy The behavior of `jsonpath2` differs from the original JSONPath spec.

In `jsonpath2`, the value at `"$..book"` is a JSON array and the value at `"$..book[*]"` is a JSON object; whereas, in the original JSONPath spec, the value at `"$..book"` would be a JSON object.

The difference in behavior means that, in `jsonpath2`, both the JSON array and its elements are uniquely identifiable; whereas, in the original JSONPath spec, the JSON array is not identifiable.

**Comment by SimplicityGuy** [comment]
Makes sense; thank you for the explanation!
